version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  elasticsearch:
    image: triberay/elasticsearch-4-liferay
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  httpd:
    image: triberay/httpd-4-liferay
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "80:80"
      - "443:443"
  mockmock:
    image: triberay/mockmock-4-liferay
    networks:
      - "www-external"
      - "www-internal"
    expose:
      - "25"
    ports:
      - "8282:8282"
  liferay:
    build: .
    image: triberay/liferay-portal
    container_name: liferay-portal
    depends_on:
      - "postgres"
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8000:8000"
      - "11311:11311"
      - "12345:12345"
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_lass_UPPERCASEN_ame=org.postgresql.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:postgresql://postgres:5432/lportal
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=liferay
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=passw0rd
    volumes:
      - "./build-resources/config:/docker-init.d/config"
      - "./build-resources/script:/docker-init.d/script"
      - "./resources/deploy:/opt/liferay/deploy"
      - "./resources/osgi/modules:/opt/liferay/osgi/modules"
      - "./resources/osgi/war:/opt/liferay/osgi/war"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "5433:5432"

volumes:
  liferay: